Encoder 작성완료
TeamTailHead/TailHeadCommunicator pull request #7
Opened 2022-11-03 10:56 UTC by Fixtar

Binary encoder, decoder 작성완료

2022-11-04 02:36 UTC, Tekiter requested changes

2022-11-04 02:36 UTC, Tekiter commented on src/encoder/serverencoder/systemChat.ts
> +    else levelNo = 3;
let으로 이렇게 하지 말고, 변환용 데이터를 빼는거 어때?

```ts
const levels: Array<SystemChat['level']> = ["info", "warning", "error"]
```
선언하고
```ts
const levelNo = levels.findIndex(level)
```

2022-11-04 02:36 UTC, Tekiter commented on src/encoder/serverencoder/systemChat.ts
> +    else level = "error";
여기는 이렇게
```ts
const level = levels[levelNo];
```

2022-11-04 11:00 UTC, Fixtar commented on src/encoder/serverencoder/systemChat.ts
> +    else levelNo = 3;
오 알겠습니다

2022-11-04 19:18 UTC, Tekiter commented on src/encoder/serverencoder/systemChat.ts
> +    else levelNo = 3;
아 내가 잘못된 함수를 썼네..
`const levelNo = levels.indexOf(level)` 이렇게다

2022-11-07 10:59 UTC, Tekiter requested changes

2022-11-07 10:59 UTC, Tekiter commented on src/encoder/serverencoder/systemChat.ts
> +    const levels: Array<SystemChat["level"]> = ["info", "error", "warning"];
전역으로 빼서 한번에 관리하자!

2022-11-07 11:25 UTC, Fixtar commented on src/encoder/serverencoder/systemChat.ts
> +    const levels: Array<SystemChat["level"]> = ["info", "error", "warning"];
넹~!

2022-11-07 11:31 UTC, Tekiter approved these changes
🚀🚀🚀

2022-11-08 07:02 UTC, Fixtar commented
> 

머지 하겠습니다 ?

2022-11-08 08:31 UTC, Tekiter commented
어프루브되면 맘대로 머지 ㄲ

2022-11-09 03:06 UTC, merged